name: GitHub Actions
on:
  push:
    branches: [ Release ]
  pull_request:
    branches: [ Release ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "该作业由${{github.event_name}}事件自动触发"
      - run: echo "此作业现在正在GitHub托管的${{runner.os}}服务器上运行"
      - run: echo "分支的名称是${{github.ref}}，存储库是${{github.repository}}"
      - name: 签出存储库代码
        uses: actions/checkout@v2
      - run: echo "${{github.repository}}存储库已克隆到运行程序"
      - name: 列出存储库中的文件
        run: |
          ls ${{ github.workspace }}
      - name: 列出Package发布的文件
        run: |
          ls Package
      - name: Build
        shell: pwsh
        run: .\build.ps1 --stable=true
      - name: Get Release Version
        shell: pwsh
        run: .\build\getReleaseVersion.ps1
      - name: Create release
        shell: pwsh
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --generate-notes ${{ env.ReleaseVersion }}
      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.GitAssemblyInformationalVersion }}
          title: Version ${{ env.GitAssemblyInformationalVersion }}
          prerelease: true
          files: |
            Package/*.nupkg
      - name: 添加GitHub源
        run: |
            dotnet nuget add source --name github "https://nuget.pkg.github.com/OWNER/index.json"
      - name: 发布到Github
        run: |
            dotnet nuget push Package/*.nupkg  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
      - name: 发布到NuGet
        run: |
             dotnet nuget push Package/*.nupkg --api-key ${{secrets.NUGET_API_KEY_GeTuiPushApiV2_ServerSDK}} --source https://api.nuget.org/v3/index.json --skip-duplicate
      - run: echo "此作业的状态为${{job.status}}"